language: python
python:
  - "3.6"
  - "3.7-dev"  # 3.7 development branch

install:
  - pip install -e .[test]
  - pip install pytest-cov codecov

script:
  - pytest --cov="json_rpc" --cov-report term-missing tests/
  - codecov
